services:
  dnsserver:
    build: dnsserver
    hostname: darthvader
    ports:
      - 127.0.0.1:53:53
    volumes:
      - ./dnsserver/named.conf.options:/etc/bind/named.conf.options
      - ./dnsserver/named.conf.local:/etc/bind/named.conf.local
      - ./dnsserver/db.starwars.lan:/etc/bind/db.starwars.lan
      - ./dnsserver/db.20.168.192:/etc/bind/db.20.168.192
    networks:
      rededns:
        ipv4_address: 172.24.0.100
    dns: 127.0.0.1

  dnssecundario:
    build: dnssecundario
    hostname: darthsidious
    ports:
      - 127.0.0.1:53:5353
    networks:
      rededns:
        ipv4_address: 172.24.0.101
    dns: 127.0.0.1


  cliente:
    build: cliente
    hostname: cliente1
    networks:
      rededns:
        ipv4_address: 172.24.0.10
    dns: 172.24.0.100

# Subred
networks:
  rededns:
    ipam:
      config:
        - subnet: 172.24.0.0/16