services:
  dnsserver:
    build: dnsserver
    hostname: darthvader

    # Para los logs utilizar el argumento -f
    # command: ["-g"]
    command: ["-f"]
    volumes:
      - ./dnsserver/named.conf.options:/etc/bind/named.conf.options
      - ./dnsserver/named.conf.local:/etc/bind/named.conf.local
      - ./dnsserver/db.starwars.lan:/etc/bind/db.starwars.lan
      - ./dnsserver/db.20.168.192:/etc/bind/db.20.168.192
      - ./dnsserver/db.24.172:/etc/bind/db.24.172
      - ./dnsserver/logs:/logs
    networks:
      rededns:
        ipv4_address: 172.24.0.100
    dns: 127.0.0.1

  dnssecundario:
    build: dnssecundario
    hostname: darthsidious
    command: ["-g"]
    # depends_on: Hace que se levante el contenedor solo si
    # el contenedor indicado ya se ha levantado
    depends_on:
      - dnsserver
    # command: ["tail", "-f /dev/null"]
    volumes:
      - ./dnssecundario/named.conf.local:/etc/bind/named.conf.local
      - ./dnssecundario/named.conf.options:/etc/bind/named.conf.options
    networks:
      rededns:
        ipv4_address: 172.24.0.101
    dns: 127.0.0.1

  leia:
    build: ./leia
    hostname: leia
    command: ["-g"]

    depends_on:
      - dnsserver

    volumes:
      - ./leia/named.conf.local:/etc/bind/named.conf.local
      - ./leia/named.conf.options:/etc/bind/named.conf.options
      - ./leia/db.imperio.starwars.lan:/etc/bind/db.imperio.starwars.lan

    networks:
      rededns:
        ipv4_address: 172.24.0.110
    dns: 127.0.0.1

  cliente:
    build: cliente
    hostname: cliente1
    networks:
      rededns:
        ipv4_address: 172.24.0.10
    dns: 172.24.0.100

    # Configurar el search (/etc/resolv.conf)
    # Si ndots vale 0 no acepta nombres relativos
    dns_opt:
      - ndots:2
    dns_search: starwars.lan

# Subred
networks:
  rededns:
    ipam:
      config:
        - subnet: 172.24.0.0/16
