services:
  dnsserver:
    build: dnsserver
    hostname: dnsserver
    ports:
      - 127.0.0.1:53:53    #So na rede principal
    volumes:
      - ./dnsserver/named.conf.options:/etc/bind/named.conf.options
      - ./dnsserver/named.conf.local:/etc/bind/named.conf.local
      - ./dnsserver/db.starwars.lan:/etc/bind/db.starwars.lan
    networks:
      rededns:
        ipv4_address: 172.24.0.100
    dns: 127.0.0.1
  cliente:
    build: cliente
    hostname: cliente1
    networks:
      rededns:
        ipv4_address: 172.24.0.10
    dns: 172.24.0.100
networks:
  rededns:
    ipam:
      config:
        - subnet: 172.24.0.0/16